### ISSUE TITLE
AssertionError: Property ro.bootimage.product.cpu.abilist could not be found in build.prop

### ISSUE THREAD

**Issue by zjm54321** [SebaUbuntu/TWRP-device-tree-generator#145]
My device is Lenovo a938t, running android 4.4.
`[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ming/.local/lib/python3.10/site-packages/twrpdtgen/__main__.py", line 11, in <module>
    main()
  File "/home/ming/.local/lib/python3.10/site-packages/twrpdtgen/main.py", line 37, in main
    device_tree = DeviceTree(image=args.image)
  File "/home/ming/.local/lib/python3.10/site-packages/twrpdtgen/device_tree.py", line 66, in __init__
    self.device_info = DeviceInfo(self.build_prop)
  File "/home/ming/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 136, in __init__
    abi_list = self.get_first_prop(DEVICE_CPU_ABILIST).split(",")
  File "/home/ming/.local/lib/python3.10/site-packages/sebaubuntu_libs/libandroid/device_info.py", line 177, in get_first_prop
    raise AssertionError(f'Property {props[0]} could not be found in build.prop')
AssertionError: Property ro.bootimage.product.cpu.abilist could not be found in build.prop
`

**Comment by rik0612c** [comment]
You could unpack the recovery.img, then unpack ramdisk, and add the missing props in default.prop. for me, it resolved this issue.

**Comment by sounddrill31** [comment]
> You could unpack the recovery.img, then unpack ramdisk, and add the missing props in default.prop. then repack the bootimg. for me, it resolved this issue.

Ideally, where can these values(for the missing props) be found?

**Comment by sounddrill31** [comment]
> use vendor_boot.img (Only for A/B devices)

My device was a kitkat phone :P

Thanks for the response tho

**Comment by Finite-Code** [comment]
> > use vendor_boot.img (Only for A/B devices)
> 
> My device was a kitkat phone :P
> 
> Thanks for the response tho

old is gold
