### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by braveone1** [SebaUbuntu/TWRP-device-tree-generator#38]
[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/twrpdtgen/__main__.py", line 28, in <module>
    dt = generate_device_tree(args.recovery_image, args.output, no_git=args.no_git, keep_aik=args.keep_aik)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/twrpdtgen/twrp_dt_gen.py", line 30, in generate_device_tree
    aik.extract(recovery_image)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/twrpdtgen/utils/aik_manager.py", line 64, in extract
    self.get_image_infos()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/twrpdtgen/utils/aik_manager.py", line 79, in get_image_infos
    self.base_address = self.read_recovery_file(self.get_extracted_info("base"))
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/twrpdtgen/utils/aik_manager.py", line 108, in read_recovery_file
    return file.read_text().splitlines()[0]
  File "/data/data/com.termux/files/usr/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/data/data/com.termux/files/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/data/data/com.termux/files/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/tmp/tmpois75698/split_img/recovery.img-base'

**Comment by SebaUbuntu** [comment]
There are now the necessary tools to debug it, reopen the issue with proper logging
