### ISSUE TITLE
Traceback error (Apparently that's it)

### ISSUE THREAD

**Issue by LichtEstarossx** [SebaUbuntu/TWRP-device-tree-generator#39]
I tried to use this generator, but I received this error, I don't understand if something I'm doing, although it's probably that, I will still leave the message that the terminal 

```
licht@q4os-desktop:~/Documentos/twrp$ python3 -m twrpdtgen recovery.img
Traceback (most recent call last):
  File "/home/licht/.local/lib/python3.7/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/home/licht/.local/lib/python3.7/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/home/licht/.local/lib/python3.7/site-packages/git/cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/licht/.local/lib/python3.7/site-packages/twrpdtgen/__main__.py", line 6, in <module>
    from twrpdtgen.device_tree import DeviceTree
  File "/home/licht/.local/lib/python3.7/site-packages/twrpdtgen/device_tree.py", line 7, in <module>
    from git import Repo
  File "/home/licht/.local/lib/python3.7/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by SebaUbuntu** [comment]
Please install git

`sudo apt install git` or `sudo pacman -S git`
