### ISSUE TITLE
FileNotFoundError: Specified file doesn't exist

### ISSUE THREAD

**Issue by Osanosa** [SebaUbuntu/TWRP-device-tree-generator#69]
osanosa@HOME-PC:~$ python3 -m twrpdtgen --no-git C:\recovery.img
TWRP device tree generator
Version 1.3.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/osanosa/.local/lib/python3.8/site-packages/twrpdtgen/__main__.py", line 52, in <module>
    dt = DeviceTree(args.output, recovery_image=args.recovery_image,
  File "/home/osanosa/.local/lib/python3.8/site-packages/twrpdtgen/device_tree.py", line 44, in __init__
    raise FileNotFoundError("Specified file doesn't exist")
FileNotFoundError: Specified file doesn't exist

**Comment by Osanosa** [comment]
I'm using WSL2

**Comment by Osanosa** [comment]
osanosa@HOME-PC:~$ sudo apt install cpio
Reading package lists... Done
Building dependency tree
Reading state information... Done
cpio is already the newest version (2.13+dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
osanosa@HOME-PC:~$ pip3 install twrpdtgen

Requirement already satisfied: twrpdtgen in ./.local/lib/python3.8/site-packages (1.3.0)
Requirement already satisfied: GitPython<4.0.0,>=3.1.14 in ./.local/lib/python3.8/site-packages (from twrpdtgen) (3.1.18)
Requirement already satisfied: Jinja2<4.0.0,>=3.0.0a1 in ./.local/lib/python3.8/site-packages (from twrpdtgen) (3.0.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.local/lib/python3.8/site-packages (from GitPython<4.0.0,>=3.1.14->twrpdtgen) (4.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.8/site-packages (from Jinja2<4.0.0,>=3.0.0a1->twrpdtgen) (2.0.1)
Requirement already satisfied: smmap<5,>=3.0.1 in ./.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->GitPython<4.0.0,>=3.1.14->twrpdtgen) (4.0.0)

**Comment by Osanosa** [comment]
I've figured it out — `cd /mnt/c` fixed it
