### ISSUE TITLE
aise AssertionError(f"Device {error} could not be found in build.prop") when generting tree from android 9.0 twrp image 

### ISSUE THREAD

**Issue by kondors1995** [SebaUbuntu/TWRP-device-tree-generator#70]
Device raphael (k20 pro)

image used  twrp-3.5.2_9-0-raphael.img

comand used python3 -m twrpdtgen -v --output OUTPUT -k  twrp-3.5.2_9-0-raphael.img

output 

nato66613@Compute:/datadrive/TWRP-device-tree-generator$ python3 -m twrpdtgen -v --output OUTPUT -k  twrp-3.5.2_9-0-raphael.img
TWRP device tree generator
Version 1.3.1

[aik_manager.py:46 INFO] __init__: Cloning AIK...
[cmd.py:814 DEBUG] execute: Popen(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/datadrive/TWRP-device-tree-generator/extract'], cwd=/datadrive/TWRP-device-tree-generator, universal_newlines=True, shell=None, istream=None)
[base.py:1048 DEBUG] _clone: Cmd(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/datadrive/TWRP-device-tree-generator/extract'])'s unused stdout:
[device_tree.py:55 DEBUG] __init__: Getting device infos...
[device_tree.py:58 DEBUG] __init__: Using /datadrive/TWRP-device-tree-generator/extract/ramdisk/default.prop as build.prop
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/datadrive/TWRP-device-tree-generator/twrpdtgen/__main__.py", line 52, in <module>
    dt = DeviceTree(args.output, recovery_image=args.recovery_image,
  File "/datadrive/TWRP-device-tree-generator/twrpdtgen/device_tree.py", line 60, in __init__
    self.build_prop_reader = BuildPropReader(self.build_prop)
  File "/datadrive/TWRP-device-tree-generator/twrpdtgen/info_extractors/buildprop.py", line 28, in __init__
    self.codename = self.get_prop(DEVICE_CODENAME, "codename")
  File "/datadrive/TWRP-device-tree-generator/twrpdtgen/info_extractors/buildprop.py", line 61, in get_prop
    raise AssertionError(f"Device {error} could not be found in build.prop")
AssertionError: Device codename could not be found in build.prop

**Comment by SebaUbuntu** [comment]
Closing for inactivity
