### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by qiurigao** [SebaUbuntu/TWRP-device-tree-generator#71]
python3 -m twrpdtgen -v
TWRP device tree generator
Version 1.3.1

usage: python3 -m twrpdtgen [-h] [-o OUTPUT] [-k] [--no-git] [--huawei]
                            [--recovery_kernel RECOVERY_KERNEL]
                            [--recovery_ramdisk RECOVERY_RAMDISK]
                            [--recovery_vendor RECOVERY_VENDOR] [-v]
                            [recovery_image]
python3 -m twrpdtgen: error: the following arguments are required: recovery_image

**Comment by qiurigao** [comment]
python -m twrpdtgen recovery.img
TWRP device tree generator
Version 1.3.1

[INFO] Cloning AIK...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lenovo/.local/lib/python3.9/site-packages/twrpdtgen/__main__.py", line 52, in <module>
    dt = DeviceTree(args.output, recovery_image=args.recovery_image,
  File "/home/lenovo/.local/lib/python3.9/site-packages/twrpdtgen/device_tree.py", line 49, in __init__
    aik.extract(recovery_image)
  File "/home/lenovo/.local/lib/python3.9/site-packages/twrpdtgen/utils/aik_manager.py", line 79, in extract
    raise RuntimeError(f"AIK extraction failed, return code {returncode}")
RuntimeError: AIK extraction failed, return code 1
