### ISSUE TITLE
AssertionError: Couldn't find any build.prop [oppo CPH909]

### ISSUE THREAD

**Issue by J0shua-code** [SebaUbuntu/TWRP-device-tree-generator#77]
Device : Oppo A5s
Model : CPH1909

recovery : https://we.tl/t-FHw6tMc3G1

-----------------------------------------------------------------------------

python3 -m twrpdtgen -o Oppo -v recovery.img
TWRP device tree generator
Version 1.3.1

[aik_manager.py:46 INFO] __init__: Cloning AIK...
[cmd.py:832 DEBUG] execute: Popen(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/tmp/tmp9q3159yw'], cwd=/home/josh/Desktop/TWRP-device-tree-generator, universal_newlines=True, shell=None, istream=None)
[base.py:1085 DEBUG] _clone: Cmd(['git', 'clone', '-v', 'https://github.com/SebaUbuntu/AIK-Linux-mirror', '/tmp/tmp9q3159yw'])'s unused stdout:
[device_tree.py:55 DEBUG] __init__: Getting device infos...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/josh/Desktop/TWRP-device-tree-generator/twrpdtgen/__main__.py", line 52, in <module>
    dt = DeviceTree(args.output, recovery_image=args.recovery_image,
  File "/home/josh/Desktop/TWRP-device-tree-generator/twrpdtgen/device_tree.py", line 57, in __init__
    raise AssertionError("Couldn't find any build.prop")
AssertionError: Couldn't find any build.prop

**Comment by J0shua-code** [comment]
Thanks dev for your hard work, After this tool was not working I did some digging and found out that the windows version of AIK in this build doesn't work 
If i try to run it seperately it shows this error 
"Unrecognized format. Error!"
But this error doesn't show up if we run the python script 

Eventually I managed to extract the files from recovery with binwalk and patched the script with hardcoded paths to files and was able successfully compile twrp for my device.

This tool definitely saved me some time,also would be be nice to have a option to manually provide the script with build prop and other files
